export const VIDEO_ITEMS = [
  {
    title: 'BMW Films',
    videoId: 'wTjB4bLzHKo',
    category: 'brands',
    description: 'Premium motorcycle brand campaign',
  },
  {
    title: 'Premium Automotive',
    videoId: '1ZVsxIGs1Kg',
    category: 'brands',
    description: 'Luxury car brand showcase',
  },
  {
    title: 'Corporate Identity',
    videoId: 'lyBQYLtnKdM',
    category: 'brands',
    description: 'Corporate brand storytelling',
  },
  {
    title: 'MamaEarth Campaign',
    videoId: 'eHpSFNNhn2s',
    category: 'brands',
    description: 'Natural skincare brand film',
  },
  {
    title: 'IDBI Federal Marathon',
    videoId: 'Ll846ArEzAQ',
    category: 'events',
    description: 'Major sports event coverage',
  },
  {
    title: 'Corporate Event',
    videoId: 'R_-MOeWMfvU',
    category: 'events',
    description: 'Professional event documentation',
  },
  {
    title: 'Business Event',
    videoId: 'NvVb90pZma8',
    category: 'events',
    description: 'Corporate gathering highlights',
  },
  {
    title: 'Backpackers',
    videoId: 'a5rx0gaw7q0',
    category: 'shows',
    description: 'Travel adventure series',
  },
  {
    title: 'Industry Event',
    videoId: 'LIwleNZaumw',
    category: 'events',
    description: 'Business conference coverage',
  },
  {
    title: 'Product Launch',
    videoId: 'PmX_y3ApaDs',
    category: 'brands',
    description: 'New product unveiling event',
  },
  {
    title: 'Music Production',
    videoId: 'xVWPOQwVlNE',
    category: 'music',
    description: 'Hip-hop music video',
  },
  {
    title: 'Thana Sadar',
    videoId: 'cIGYh-SQjkA',
    category: 'shows',
    description: 'Drama series production',
  },
  {
    title: 'Brand Story',
    videoId: '_QY7YDY7jPQ',
    category: 'brands',
    description: 'Corporate brand narrative',
  },
  {
    title: 'Modern Parivar',
    videoId: 'gJCenfE8qOg',
    category: 'shows',
    description: 'Family drama series',
  },
  {
    title: 'Corporate Film',
    videoId: '4P_0BSWME5E',
    category: 'brands',
    description: 'Business showcase video',
  },
  {
    title: 'Roomies Season 3',
    videoId: 'C8RKIBQoEng',
    category: 'shows',
    description: 'Comedy web series',
  },
  {
    title: 'Marketing Campaign',
    videoId: '8rmFk1dHb_M',
    category: 'brands',
    description: 'Brand marketing film',
  },
  {
    title: 'Product Campaign',
    videoId: 'BoUIN4WyCO0',
    category: 'brands',
    description: 'Product promotional video',
  },
  {
    title: 'Brand Event',
    videoId: 'HGBksIItYQs',
    category: 'events',
    description: 'Corporate event highlights',
  },
  {
    title: 'Corporate Series',
    videoId: 'CdBX0NTjlII',
    category: 'brands',
    description: 'Business documentary series',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Works' },
  { id: 'brands', label: 'Brand Films' },
  { id: 'shows', label: 'Web Series' },
  { id: 'events', label: 'Events' },
  { id: 'music', label: 'Music Videos' },
];
